test/components/user_list_test.js
web/static/js/components/user_list.jsx
web/static/js/components/user_list_item.jsx

Simplest thing for now. The guests are ordered by online_at - we're just tagging the first one as the Facilitator.

Label user with the earliest online_at time as the Facilitator

---

mix.exs
mix.lock
test/channels/retro_channel_test.exs
test/features/existing_ideas_rendered_on_joining_retro_test.exs
test/features/lobby_realtime_update_test.exs
test/features/retro_idea_realtime_update_test.exs
test/support/integration_case.ex
test/support/test_helpers.ex

**NOTE**: This bump will generate a ton of warnings.  I'll address those in a followup PR.
Gives us some nice new features in the API

Bump wallaby

---

.eslintrc.js
test/components/idea_list_item_test.js
test/components/idea_submission_form_test.js
test/components/room_test.js
test/components/stage_progression_button_test.js
web/static/js/components/category_column.jsx
web/static/js/components/idea_list_item.jsx
web/static/js/components/idea_submission_form.jsx
web/static/js/components/remote_retro.jsx
web/static/js/components/room.jsx
web/static/js/components/stage_progression_button.jsx
web/static/js/components/user_list.jsx
web/static/js/components/user_list_item.jsx
web/static/js/prop_types.js

@vanderhoop 
- Modified a few eslint rules for sanity's sake
- Left 3 PropTypes lint errors in place, as they require larger-scale
refactoring of the component lifecycles (React -> Redux)
- Left confirm() warning in place

Application-wide delinting

---

test/components/user_list_item_test.js
web/static/js/components/css_modules/user_list_item.css
web/static/js/components/user_list_item.jsx

added user icons to user_list_item

---

test/controllers/retro_controller_test.exs
web/controllers/retro_controller.ex

Only create a user<>retro participation once

---

lib/remote_retro/emails.ex
test/features/send_action_item_to_users_via_email_test.exs

Improve action item email formatting 

---

test/actions/user_actions_test.js
test/reducers/user_reducer_test.js
web/static/js/actions/user.js
web/static/js/reducers/user.js

@vanderhoop 
Yo dude. small PR here to update user reducer + action creator to handle array of users/presences rather than one user at a time. This approach is in greater parity with the Presence data being passed from the Phoenix channel

Update user reducer + action creator to handle array of users/presences

---

test/actions/idea_actions_test.js
test/reducers/idea_reducer_test.js
web/static/js/actions/idea.js
web/static/js/reducers/idea.js

hey @caporta @crq @samdec11 @kimberlysuazo, thought i'd open a tiny PR for augmenting our ideas action creator and reducer so that it can handle the initial setting of pre-existing ideas when joining an in-progress retro. I'm new to redux, and while I think I'm on point, I appreciate any feedback. thanks!

Redux migration/augment ideas reducer

---

web/static/css/tiny_modal.css
web/static/js/components/stage_progression_button.jsx
webpack.config.js

Hey Travis!
I was able to pull in the tiny modal styling into app.js. I was not able to get it to work as a separate css file however. Let me know if this is sufficient or not.
Thanks!
Tanya

Add tiny modal styling to app and use in progression confirmation - story# 198

---

.github/PULL_REQUEST_TEMPLATE.md

__Description of Change(s) Introduced:__ Adds a pull request template for all contributors to the remote retro repo to see moving forward
- [issue 210](https://github.com/stride-nyc/remote_retro/issues/210)

[issue 210] Add pull request template

---

web/static/css/app.css
web/templates/page/index.html.eex

Hey Travis!
I chose gray for the ribbon color. Let me know if you prefer another color.
Thanks!
Tanya

Add 'Fork me on Github' ribbon to landing page - story# 204

---

package.json
postcss.config.js
webpack.config.js
yarn.lock

Hey Travis!
This PR brings in a postCSS plugin via Webpack in order to allow CSS nesting. 
Let me know if it's good to go!
Thanks,
Tanya

Bring in postCSS plugin to allow for nested css - story# 215

---

circle.yml

__Description of Change(s) Introduced:__ I added continuous deployment config to circle.yml. I also followed the other steps [here]( https://circleci.com/docs/1.0/continuous-deployment-with-heroku/ ) so I think it should work!
#212

add continuous deployment config to circle.yml

---

priv/repo/migrations/20170807171934_add_index_to_user_id_and_retro_id.exs
web/models/participation.ex

Hey Travis!
Let me know if this is good to go. As per our discussion, I may not have enough rows for the index search to kick in (https://stackoverflow.com/questions/5203755/why-does-postgresql-perform-sequential-scan-on-indexed-column).
Thanks!
Tanya

Add composite index to participations table - story#222

---

test/channels/retro_channel_test.exs
test/components/idea_generation_lower_third_test.js
web/channels/retro_channel.ex
web/models/retro.ex
web/static/js/components/category_column.jsx
web/static/js/components/idea.jsx
web/static/js/components/idea_generation_lower_third.jsx
web/static/js/configs/stage_configs.jsx

Hey Travis!
Let me know if this is good to go!
Thanks,
Tanya

Close retros upon entering the 'action-item-distribution' phase - #182

---

test/channels/retro_channel_test.exs
test/components/idea_generation_lower_third_test.js
web/channels/retro_channel.ex
web/models/retro.ex
web/static/js/components/category_column.jsx
web/static/js/components/idea.jsx
web/static/js/components/idea_generation_lower_third.jsx
web/static/js/configs/stage_configs.jsx

Reverts stride-nyc/remote_retro#238

Revert "Close retros upon entering the 'action-item-distribution' phase - #182"

---

test/channels/retro_channel_test.exs
test/components/category_column_test.js
test/components/idea_board_test.js
test/components/idea_generation_lower_third_test.js
test/components/idea_test.js
web/channels/retro_channel.ex
web/models/retro.ex
web/static/js/components/category_column.jsx
web/static/js/components/idea.jsx
web/static/js/components/idea_board.jsx
web/static/js/components/idea_generation_lower_third.jsx
web/static/js/configs/stage_configs.jsx

__Description of Change(s) Introduced:__ renamed action-item-distribution stage to closed
- #182

rename action-item-distribution stage to closed

---

Procfile

__Description of Change(s) Introduced:__ Added the release step in the Procfile to run migrations as a deploy step.
__Relevant github Issue:__ Issue https://github.com/stride-nyc/remote_retro/issues/265

Run migrations on deploy

---

lib/tasks/preflight.ex

__Description of Change(s) Introduced:__ update mix version requirement to 0.17.x in preflight task
__Dependencies Introduced or Upgraded:__ 
- Mix - 0.17.1

update mix version requirement to 0.17.x

---

package.json
web/static/js/components/animated_ellipsis.jsx

Hi @vanderhoop et al.,
Was creeping and saw the tiniest of opportunities to contribute.
Refactor the application of classnames in the animated ellipses component
n/a
n/a
Don't know if I missed a unit test here. LMK if there's room for improvement.
😁 
n/a

Ellipses class names

---

web/static/js/components/door_chime.jsx
web/static/js/components/room.jsx
web/static/js/configs/stage_configs.jsx
web/static/js/configs/stages.js
web/static/js/prop_types.js
web/static/js/reducers/stage.js

This PR replaces magic strings with constants for stages on the front-end
No new dependencies
No modified tests

Refactor front-end by replacing magic strings with constants for stages - story# 230

---

README.md

__Description of Change(s) Introduced:__ Updated README to include React in app description
__Dependencies Introduced or Upgraded:__ n/a
__Description of Testing Applied:__ n/a
__Relevant Screenshots/GIFs:__ n/a
__Relevant github Issue:__ n/a

Update README to include React in app description

---

lib/remote_retro/emails.ex
test/features/send_action_item_to_users_via_email_test.exs
test/support/test_helpers.ex

This PR persists assignee name next to each action item in the action item emails.
__Dependencies Introduced or Upgraded:__ (if applicable) n/a
__Description of Testing Applied:__ (if applicable) the corresponding feature test was updated but needs refactoring
- [249](https://github.com/stride-nyc/remote_retro/issues/249)

Include action items assignee name in the outgoing emails

---

test/channels/retro_channel_test.exs
test/components/idea_edit_form_test.js
test/components/idea_submission_form_test.js
test/components/idea_test.js
web/channels/retro_channel.ex
web/models/idea.ex
web/static/js/components/idea.jsx
web/static/js/components/idea_edit_form.jsx
web/static/js/components/idea_submission_form.jsx
web/static/js/components/select_dropdown.jsx

__Description of Change(s) Introduced:__ Facilitators now have the ability to edit the assignee of an action item.
__Description of Testing Applied:__ Frontend component tests and backend to ensure expected messages are received and handled accordingly, changing the assigned assignee_id
- #350

Edit action item assignee

---

lib/remote_retro_web/templates/layout/app.html.eex

Update Built by Stride link in header to open in new tab
n/a
n/a
n/a
- [issue (404)](https://github.com/stride-nyc/remote_retro/issues/404)

Update Built by Stride link to open in new tab

---

.pairs

Add jenn and anurup to pairs

---

web/static/js/components/stage_change_info_groups_voting.jsx

Fixed spacing in the UI for text when doing voting on groups.

NONE: - Fixed spacing for UI text when doing voting

---

.pairs
LICENSE
README.md
lib/remote_retro/emails.ex
lib/remote_retro_web/plugs/forbid_non_striders.ex
lib/remote_retro_web/templates/layout/app.html.heex
lib/remote_retro_web/templates/page/index.html.heex
lib/remote_retro_web/templates/page/privacy.html.heex
test/plugs/forbid_non_striders_test.exs

Use Stride's new domain. Also allow for stride.build email addresses to work as well.
- [issue (number)](issue_url)

switch to using stride.build instead of stridenyc.com

---

.circleci/config.yml
config/test.exs
mix.exs

Fixes mix feature tests in the CI.

Fix mix feature tests
