stride-nyc/remote_retro

priv/repo/migrations/20170205181507_add-retros-table.exs, web/controllers/auth_controller.ex, web/oauth/google.ex
Running migrations throws a few errors about naked variables.  This PR cleans those up.
=> Fix compiler warnings

web/static/js/components/category_column.jsx, web/static/js/components/door_chime.jsx, web/static/js/components/room.jsx, web/static/js/components/user_list.jsx, web/static/js/components/user_list_item.jsx, web/static/js/prop-types.js
Helps with:
- Ensuring the contract, via props, for domain-specific objects and data types
- DRY as the desert
- This thing called testing
This pattern helped a lot at a couple Stride clients 👌.
=> Move app-specific prop types to own file

web/static/js/components/category_column.jsx, web/static/js/components/idea.jsx, web/static/js/components/idea_controls.jsx, web/static/js/components/room.jsx, web/static/js/components/user_list.jsx, web/static/js/components/user_list_item.jsx
Some stateless components were using the old `function` syntax. Here I've converted them into `const`s.
=> Convert stateless components to ES6 consts

test/actions/idea_actions_test.js, test/actions/retro_actions_test.js, test/components/remote_retro_test.js, test/reducers/idea_reducer_test.js, test/reducers/inserted_at_test.js, test/reducers/stage_reducer_test.js, web/static/js/actions/idea.js, web/static/js/actions/retro.js, web/static/js/components/remote_retro.jsx, web/static/js/reducers/idea.js, web/static/js/reducers/index.js, web/static/js/reducers/inserted_at.js, web/static/js/reducers/stage.js
This PR shifts the remainder of `RemoteRetro` component's local state (`stage` and `inserted_at`) to the redux store!
In doing this work, we introduce a new action, `SET_INITIAL_STATE`, that allowed two additional refactors: 
1. make a single dispatch from the retroChannel's join callback
1. delete the "SET_IDEAS" action and reducer case, as the case that called for it is now handled by `SET_INITIAL_STATE`, which handles setting `ideas`, `stage`, and `insertedAt` on the store
=> Kill RemoteRetro's local state in favor of redux store

.eslintrc.js, test/.eslintrc.json, test/actions/retro_actions_test.js, test/components/remote_retro_test.js, test/components/room_test.js, web/static/js/components/category_column.jsx, web/static/js/components/remote_retro.jsx, web/static/js/components/share_retro_link_modal.jsx, web/static/js/components/stage_progression_button.jsx, web/static/js/reducers/user.js
```
remote_retro/test/actions/retro_actions_test.js
24:1  error  Too many blank lines at the end of file. Max of 1 allowed  no-multiple-empty-lines
remote_retro/test/components/remote_retro_test.js
11:9  error  'wrapper' is assigned a value but never used  no-unused-vars
remote_retro/test/components/stage_progression_button_test.js
138:7  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
remote_retro/web/static/js/app.js
8:8  error  Using exported name 'RemoteRetro' as identifier for default export  import/no-named-as-default
remote_retro/web/static/js/components/category_column.jsx
16:9  error  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/img-has-alt …
```
=> Fix remaining linter errors

web/static/js/components/remote_retro.jsx
In attempting to fix a linting issue, I set the `insertedAt` prop as required, but it turns out that it is sometimes null. Defaulting it to null allows it to function as normal and placates the linter.
=> Bugfix: Allow insertedAt to be null in RemoteRetro component

test/features/preexisting_retro_state_rendered_on_joining_retro_test.exs, test/features/retro_idea_realtime_update_test.exs, web/static/js/components/css_modules/category_column.css
=> Add scrollable columns

web/static/js/components/remote_retro.jsx, web/static/js/services/user_activity.js
After my refactor in #176, the dots are starting and stopping erratically when someone types. This stops it doing that. 
I'd wanted not to have to pass in the entire `RetroChannel` object, but because the props change within the channel, just passing in the props or the users isn't sufficient and they need to be accessed anew within the interval.
=> Bugfix: Fix the check for user typing

web/static/js/components/css_modules/category_column.css
This fixes the scrolling on the retro page so that the scrollbar only appears when a list has become too long for its container.  Otherwise, no scroll appears.  Before this change, a scrollbar would always appear.
=> Change scroll to auto

lib/tasks/preflight.ex
__Description of Change(s) Introduced:__ instead of hardcoding the version number for Hex, we should use a regex to check that `0.16.SOME_NUMBER` is being used
=> add regex for required_version_num and use Regex.match

web/static/js/configs/stage_configs.jsx
__Description of Change(s) Introduced:__ I created a Survey Monkey survey and added a link to it to the action item distribution alert. 
The survey results can be seen [here](https://www.surveymonkey.com/analyze/Sm5V2nM7ZHiVzOs34rhW81bWvjEWSpadfDicDUlGZF8_3D
).
username: remoteretro
pw: r3moter3tro8!
=> Add link to feedback survey to action item distribution alert

test/components/idea_generation_lower_third_test.js, web/static/js/components/idea_generation_lower_third.jsx
__Description of Change(s) Introduced:__ Previously the stageProgressionButton was only disabled when there were no action items. This bugfix makes it so that it is also disabled when there are no ideas.
=> Change condition for disabling the stage progression button

test/components/idea_controls_test.js, test/components/vote_counter_test.js, web/static/js/components/css_modules/vote_counter.css, web/static/js/components/idea_controls.jsx, web/static/js/components/vote_counter.jsx
__Description of Change(s) Introduced:__ using the classnames library, conditionally style the voting button so that it is clear that it is disabled when not in the voting stage. Also, actually disable the button. 
I couldn't get the cursor appearance to go back to default for the disabled button. Despite adding in the CSS for it, for some reason the div that wraps the button and label seem to ignore it. @vanderhoop do you have any ideas about what might be going on here?
#245
=> Add prop and conditionally disable button when not in voting stage

web/static/js/components/css_modules/category_column.css
__Description of Change(s) Introduced:__ Created a shadow to indicate in the category columns when scrolling is an option.
__Relevant Screenshots/GIFs:__ 
__Relevant github Issue:__ https://github.com/stride-nyc/remote_retro/issues/257
=> Create shadows on the categorgy columns to indicate scrollability

test/components/vote_counter_test.js, web/static/js/components/idea_controls.jsx, web/static/js/components/stage_change_info_voting.jsx, web/static/js/components/vote_counter.jsx
This PR introduces the following change:
- During the voting stage, users should only see their own vote count.
- After the voting stage, users should see each idea's total vote count.
Testing:
- Front-end unit tests were updated to reflect these changes.
=> Only display other users' vote counts after the voting phase - story# 277

test/actions/retro_actions_test.js, test/components/category_column_test.js, test/components/idea_board_test.js, test/components/idea_controls_test.js, test/components/idea_generation_lower_third_content_test.js, test/components/idea_submission_form_test.js, test/components/idea_test.js, test/components/lower_third_animation_wrapper_test.js, test/components/lower_third_test.js, test/components/remote_retro_test.js, test/components/room_test.js, test/components/user_list_item_test.js, test/components/vote_counter_test.js, test/services/retro_channel_test.js, test/support/js/test_helper.js, web/static/js/components/category_column.jsx, web/static/js/components/idea.jsx, web/static/js/components/idea_board.jsx, web/static/js/components/idea_controls.jsx, web/static/js/components/idea_generation_lower_third_content.jsx, web/static/js/components/idea_submission_form.jsx, web/static/js/components/lower_third.jsx, web/static/js/components/user_list_item.jsx, web/static/js/components/vote_counter.jsx
Replace all instances of magic strings with constants on the front-end for stage names.
No new dependencies.
No new tests.
story: https://github.com/stride-nyc/remote_retro/issues/230
=> Replace additional magic strings with constants for stage names - story# 230

test/components/user_list_item_test.js, test/components/votes_left_test.js, web/channels/retro_channel.ex, web/static/js/components/stage_change_info_voting.jsx, web/static/js/configs/retro_configs.js
This PR changes the max votes per user from 5 to 3.
No new dependencies.
Tests have been updated accordingly.
Relevant github Issue:
- [308](https://github.com/stride-nyc/remote_retro/issues/308)
=> Change number of max votes per user from 5 to 3

test/components/idea_board_test.js, web/static/js/components/idea_board.jsx, web/static/js/components/remote_retro.jsx, web/static/js/configs/retro_configs.js, web/static/js/prop_types.js
This PR replaces hardcoded categories in IdeaBoard with categories passed in as props.
The categories have been placed into a separate constants file.
No new dependencies.
Tests have been updated accordingly.
Relevant github Issue:
- [309](https://github.com/stride-nyc/remote_retro/issues/309)
=> Refactor categories from the IdeaBoard

test/components/lower_third_test.js, web/static/js/components/voting_lower_third_content.jsx
This PR introduces a bug fix for the overlap of participants and the ideas during the voting phase.
__Dependencies Introduced or Upgraded:__ n/a
__Description of Testing Applied:__ tests were updated for the conditional rendering
__Relevant Screenshots/GIFs:__ 
facilitator's view: 
non-facilitator's view:
__Relevant github Issue:__
- [333](https://github.com/stride-nyc/remote_retro/issues/333)
=> Bugfix/avoid overlap in voting phase - story# 333

README.md
Updated README to include G+ API link. I totally missed this on my install.
=> Add link to Google+ API to README

web/static/css/app.css, web/static/js/components/idea_submission_form.jsx, web/templates/retro/show.html.eex
I performed an accessibility audit (screenshots below), and found some low-hanging fruit, so I:
Added alt text to an image. Fixed a label tie. Added a label to an un-labeled input.
<s>A great todo would be to remove the divs from inside the lists (think that has to do with a scrolling component).</s> #344.
paging @imaginista on the color contrast issue. also, hey Brett!
Re-ran audit, with higher score (see below)
=> Accessibility audit idea gen

.eslintrc.js, test/components/idea_controls_test.js, web/static/js/components/idea_controls.jsx
This PR introduces the following changes:
1) The facilitator's edit, delete, and spotlight idea control icons become disabled while the author is editing their idea
2) When hovering over the deactivated idea control icons, the title tooltip displays "Author currently editing"
3) When hovering over active idea control icons, the title tooltip displays "Delete Idea" or "Edit Idea", depending on the icon type.
__Dependencies Introduced or Upgraded:__ n/a
__Description of Testing Applied:__ Tests updated accordingly
- [331](https://github.com/stride-nyc/remote_retro/issues/331)
=> Disallow facilitators from acting on idea while it is being edited by its author

web/static/js/components/category_column.jsx, web/static/js/components/idea.jsx, web/static/js/components/idea_submission_form.jsx
Following up on #343 (and branched off of), this removes the wrapping elements inside an idea list.
It also boosts accessibility of the idea generation page to 97 (screenshot below).
=> Accessible idea list

.babelrc, package.json, test/components/category_column_test.js, test/components/idea_read_only_content_test.js, web/static/js/components/category_column.jsx, web/static/js/components/idea_read_only_content.jsx, yarn.lock
Adds drag-and-drop to an Idea, re:  #336.
[babel-preset-stage-2](https://babeljs.io/docs/plugins/preset-stage-2/), can remove/break up dependency since it's not required, but it's become pretty handle and widely used for class-properties.
migrated babel-preset-es2015 to -env (recommended from babel)
Unit tests. Manually confirmed in latest Safari, Firefox, and Chrome.
#336
=> Drag an Idea

priv/repo/migrations/20180105152248_add_lobby_stage.exs, test/components/lobby_stage_test.jsx, test/components/room_test.js, test/features/stage_progression_realtime_update_test.exs, web/models/retro.ex, web/static/js/components/css_modules/centered_text.css, web/static/js/components/lobby_stage.jsx, web/static/js/components/prime_directive.jsx, web/static/js/components/prime_directive_stage.jsx, web/static/js/components/room.jsx, web/static/js/components/stage_change_info_prime_directive.jsx, web/static/js/configs/stage_configs.jsx, web/static/js/configs/stages.js, web/static/js/prop_types.js
Retros now begin with a Lobby stage, which gives one set of instructions for the facilitator and a separate set for the participants.
__Description of Testing Applied:__
- Unit tests for LobbyStage component
__Relevant Screenshots/GIFs:__
_Facilitator_:
_Participant_:
- #298
=> Start Retros in Lobby Stage

package.json, webpack.config.js, yarn.lock
If you use `copy-webpack-plugin` from `webpack-dev-server`, "copied" files will be served from `OUTPUT_PUBLIC_PATH`, as defined in the webpack's config. We need the files written disk because Phoenix is serving the assets (not webpack). So this PR adds `write-file-webpack-plugin`, which writes to disk. This plugin [has no effect](https://github.com/gajus/write-file-webpack-plugin) when `webpack` is used instead of `webpack-dev-server`, so I think we're all good if this config file is re-used.
See: [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin#faq) for docs.
Start using `write-file-webpack-plugin` in `webpack.config.js`.
- write-file-webpack-plugin - ^4.2.0 …
=> Serve local images from priv/assets

test/components/idea_edit_form_test.js, test/components/idea_submission_form_test.js, web/static/js/components/idea_edit_form.jsx, web/static/js/components/idea_submission_form.jsx
__Description of Change(s) Introduced:__  The user is now limited to input or edit an idea of up to 255 characters in order for an idea to correctly persist in the database.
__Description of Testing Applied:__  Tests were updated accordingly.
- [issue (318)](https://github.com/stride-nyc/remote_retro/issues/318)
=> Restrict inputted and edited idea to 255 characters to match database

circle.yml
- coveralls submissions on builds triggered by forked repos would cause barf coveralls to barf, breaking the build
- the workaround is to only submit to coveralls in cases where the repo in question has a coveralls token.
- [issue (number)](issue_url)
=> Workflow: allow CircleCI to review pull requests from forked repos

test/components/select_dropdown_test.js, web/static/js/components/css_modules/idea_submission_form.css, web/static/js/components/idea_edit_form.jsx, web/static/js/components/idea_submission_form.jsx, web/static/js/components/select_dropdown.jsx
This PR displays an asterisk next to the required form labels: 'Assignee' and 'Category'.
__Description of Testing Applied:__ front-end test has been updated accordingly
__Relevant Screenshots/GIFs:__ 
- [issue (368)](https://github.com/stride-nyc/remote_retro/issues/368)
=> Display 'required' asterisk next to the 'Assignee' and 'Category' labels

.gitignore, test/components/user_list_item_test.js, web/static/js/components/remote_retro.jsx, web/static/js/components/user_list_item.jsx
* Disable alert and label of (Facilitator) for facilitation transfer when retro is in stage=closed
- [issue (376)](https://github.com/stride-nyc/remote_retro/issues/376)
=> disable alert for facilitation transfer on closed stage

web/static/js/components/alert.jsx
__Description of changes introduced:__
The following warning is shown in both the console and the e2e test output: 
` react-modal: App element is not defined. Please use `Modal.setAppElement(el)` or set `appElement={el}`. This is needed so screen readers don't see main content when modal is opened. It is not recommended `
This fix will set the element before the render with `componentWillMont()`
A few references: 
https://github.com/reactjs/react-modal/issues/133
https://stackoverflow.com/questions/48269381/warning-react-modal-app-element-is-not-defined-please-use-modal-setappeleme
https://github.com/reactjs/react-modal/issues/576
=> Fix modal warning in console and tests

test/channels/retro_channel_test.exs, test/components/idea_edit_form_test.js, test/features/retro_idea_realtime_update_test.exs, test/support/integration_case.ex, test/support/test_helpers.ex, test/support/user_retro_case.ex, web/static/js/components/idea_edit_form.jsx
- Update IdeaEditForm to hide live edits for ideas authored by facilitator
- Reinstate timer.sleep call when instantiating chrome sessions
- Update user_retro_case to add two users: facilitator and non_facilitator
- Update persist_idea_for_retro to allow for second user as idea author
- [issue 475](https://github.com/stride-nyc/remote_retro/issues/475)
=> Hide live edits for ideas authored by facilitator

.tool-versions, README.md
`asdf` is an agnostic version management tool.
It would make sense to move to using it over `nvm` since that is already introduced for Elixir.
`asdf-nodejs` - added
`nvm` - removed
Ran on my system with exact copy/paste, installed the things, checked that it worked.
n/a
n/a
=> Favor `asdf` over `nvm` for version management of NodeJS

lib/remote_retro_web/models/idea.ex, test/models/idea_test.exs
When an `Idea` is created or modified, require that an `assignee_id` is present if the `Idea` is an `action-item`.
__Description of Testing Applied:__
3 unit tests for new validation on `Idea` model.
- issue #413
=> Validate presence of assignee_id on Idea when an action-item

test/components/user_list_test.js, web/static/js/components/centered_text_stage_wrapper.jsx, web/static/js/components/css_modules/user_list.css, web/static/js/components/idea_generation_stage.jsx, web/static/js/components/user_list.jsx
Adds some CSS to allow lobby guests to wrap to multiple rows in the lobby and prime directive stages
`UserList` now takes a `wrap` property that toggles which form of the `UserList` you receive
https://github.com/stride-nyc/remote_retro/issues/453
=> Make user lobby guests wrap around

lib/remote_retro_web/templates/layout/app.html.eex, test/components/remote_retro_test.js, test/components/stage_help_test.js, test/redux/alert_test.js, web/static/css/app.css, web/static/js/components/remote_retro.jsx, web/static/js/components/stage_help.jsx, web/static/js/configs/stage_configs.jsx, web/static/js/prop_types.js, web/static/js/redux/alert.js, web/static/js/redux/retro.js
- Adds a question mark icon to the header which, when clicked,
invokes the stage breakdown modal for the current retro stage.
- Adds a new redux action for alerts to invoke help.
- Adds a new 'help' key to the stageConfig.js to show abbreviated
header for the help modal (does not show "Stage Change! when it
is help).
- Since the header exists outside of the react dom, uses a React
portal to render the question icon.
- Quesion mark icon renders conditionally based on stage, only
showing when there is help to be shown.
__Description of Testing Applied:__
Enzyme tests for new `StageHelp` component.
- Issue #489
=> Allow users to access stage breakdowns for help

web/static/js/configs/happy_sad_confused_stage_configs.js, web/static/js/configs/start_stop_continue_stage_configs.js
Change "you're" to "we're" to sound more inclusive and welcoming.
=> Change "you're" to "we're" to sound more inclusive and welcoming.

test/redux/mobile_test.js, web/static/js/redux/mobile.js
- I noticed while in the "Start/Stop/Continue" format in the mobile view the default behavior does not show the list items (see below image). To address this I changed the default state to an empty object and update the state to the appropriate value (`"start"` / `"stop"`) when the `SET_INITIAL_STATE` action is fired.
- N/A
- Updated default initial state
- Updated the tests to determine which selectedCategoryTab to apply when the application bootstraps
- No issue filed - let me know if you would like for me to file an issue for your records
=> sets default view to "start" in mobile view

test/components/stage_progression_button_test.js, web/static/js/components/centered_content_lower_third_wrapper.jsx, web/static/js/components/css_modules/stage_progression_button.css, web/static/js/components/stage_progression_button.jsx, web/static/js/configs/happy_sad_confused_stage_configs.js, web/static/js/configs/start_stop_continue_stage_configs.js
Hey! 
I'm not sure if this issue has already been claimed but thought I'd give it a shot! I'm looking to contribute to more open source projects and this looked liked a great place to start. I had a bunch of fun navigating the code and implementing this feature. I'm very open to your feedback and suggestions on the approach here. I have a couple of line-level questions that I've added in comments.
Peter
- N/A
- No tests added yet
- [#435](https://github.com/stride-nyc/remote_retro/issues/435)
=> notifies facilitator if all votes are cast - Addresses issue #435

lib/tasks/end_to_end.ex
**Description of Change(s) Introduced:**
```
As a developer 
I want to know when chromedriver is out of date
So that I can determine the cause of failing end to end tests
```
When chromedriver is out of date, it often fails all e2e tests. I would like to make this gotcha easier to debug going forwards.
I have added a function in the `end_to_end` task that prints out a warning when `chromedriver` is present in the global npm outdated list. 
I have chosen to allow the tests to continue to run because it is possible that an outdated chromedriver version doesn't fail the tests.
**Dependencies Introduced:**
N/A
**Description of Testing Applied:**
manual testing, via execution of `mix e2e`
=> Print warning to stdout when chromedriver is outdated

lib/remote_retro_web/models/user.ex
- Fixes issue with new users authenticating with Google OAuth getting a 500. Google stopped sending locale, which was a required field. Now we supply a default as a hotfix.
__Description of Testing Applied:__
- Local testing replicates the 500 similar to #595 and the default value resolves it.
- #595
=> Make locale an optional user field to fix auth error

.buildpacks
- The old heroku-buildpack-phoenix-static buildpack is EOL and replaced with gigalixir-buildpack-phoenix-static. See https://www.gigalixir.com/blog/end-of-life-phoenix-buildpack/
- Needed to address [broken deployment](https://app.circleci.com/pipelines/github/stride-nyc/remote_retro/343/workflows/e0aa7f33-9629-4ccd-9eb7-3c101ecbb201/jobs/3779)
=> Use non-deprecated buildpack

webpack.prod.config.js
- Pass [terserOptions](https://webpack.js.org/plugins/terser-webpack-plugin/#terseroptions) to TerserPlugin properly for v5 of plugin.
- Import [webpack-merge](https://github.com/survivejs/webpack-merge?tab=readme-ov-file#mergeconfiguration--configuration) properly for new version and cease use of smart merge, which has been removed.
=> Fix npm run compile-production

.tool-versions, phoenix_static_buildpack.config
- Busts cache in Phoenix buildpack ([docs](https://github.com/gigalixir/gigalixir-buildpack-phoenix-static?tab=readme-ov-file#configuration))
- Pins the npm and yarn versions to those that work locally for production build
- Synchronizes local dev node version with buildpack version
=> Bust cache and update pins in phoenix buildpack

.buildpacks
- given the source code dependency upgrade reversions that went in in the last PR, the specific buildpack update that was made in https://github.com/stride-nyc/remote_retro/pull/624 no longer _needed_ to be reverted
=> Use the recommended asset buildpack from gigalixir 🤦🏻‍♂️
